In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('onewayoranother2.csv')
df = df.drop(['Unnamed: 0','playcount','userid'],axis=1)
df = df.sort_values('popularity')
df = df.drop_duplicates(subset='name',keep = 'last')
df = df.reset_index(drop=True)

In [3]:
df.head(1)

acousticness                                            name  danceability  \
0         0.702  Kapitel 10 - In der Osternacht Anton Tschechow         0.586   

      tempo  loudness  energy                      id  instrumentalness  key  \
0  0.003539 -0.004339   0.103  2bB8AoMI30VKEnF2sVKxrg               0.0  5.0   

   liveness  popularity  speechiness  valence    year          artists  \
0     0.711         0.0        0.945    0.385  1953.0  Anton Tschechow   

                  genres  
0  ['german literature']

In [4]:
from sklearn.preprocessing import StandardScaler
X = np.array(df.drop(['name','id','artists','genres','year'],axis=1))
X_scaled = StandardScaler().fit_transform(X)

In [5]:
features = X_scaled.T
cov_matrix = np.cov(features)

In [6]:
cov_matrix

array([[ 1.00000639e+00, -2.62511734e-01, -2.04981473e-01,
        -5.61549547e-01, -7.47402258e-01,  3.28664120e-01,
        -2.21540237e-02, -2.38101062e-02, -5.90117858e-01,
        -5.53919564e-02, -1.77068897e-01],
       [-2.62511734e-01,  1.00000639e+00, -3.80864845e-03,
         2.90040154e-01,  2.15954349e-01, -2.78286933e-01,
         2.28070508e-02, -1.04574229e-01,  2.12836226e-01,
         2.29559933e-01,  5.58660117e-01],
       [-2.04981473e-01, -3.80864845e-03,  1.00000639e+00,
         2.11156291e-01,  2.49341011e-01, -1.05523136e-01,
         3.29563923e-03,  6.54489134e-03,  1.34922941e-01,
        -1.33974229e-02,  1.69165560e-01],
       [-5.61549547e-01,  2.90040154e-01,  2.11156291e-01,
         1.00000639e+00,  7.81261134e-01, -4.08092101e-01,
         2.21589573e-02,  5.09406853e-02,  4.59695645e-01,
        -1.15523467e-01,  3.04769348e-01],
       [-7.47402258e-01,  2.15954349e-01,  2.49341011e-01,
         7.81261134e-01,  1.00000639e+00, -2.80506726e-01,
  

In [7]:
values, vectors = np.linalg.eig(cov_matrix)


In [8]:
values

array([3.41324295, 1.47287244, 0.12394501, 0.28793775, 0.36338736,
       0.54528865, 1.16002951, 0.74974762, 0.87520579, 1.01035858,
       0.9980546 ])

In [9]:
vectors

array([[-0.44090567,  0.15272914,  0.39370103,  0.44351541,  0.52788223,
        -0.06624628, -0.09549135,  0.31829569, -0.10148883,  0.16337054,
         0.01003477],
       [ 0.2674372 ,  0.54789173,  0.17456387, -0.47719131,  0.31774041,
        -0.39703181, -0.28325196, -0.09373628, -0.06748417, -0.13013272,
         0.03174707],
       [ 0.17568971, -0.09368035,  0.01526383, -0.10458604,  0.10593483,
        -0.19890497,  0.08221118,  0.06799501,  0.63547184,  0.69273106,
         0.05759975],
       [ 0.45214971, -0.1134651 , -0.45708554,  0.05973002,  0.62590371,
         0.35349032,  0.01452649,  0.11027033, -0.19373107,  0.05963665,
         0.00466479],
       [ 0.46951797, -0.15080077,  0.74315295,  0.04517582, -0.03244357,
         0.31024058,  0.12275581, -0.21702592, -0.17406869,  0.11230627,
        -0.01054449],
       [-0.29264149, -0.14660338, -0.11559833,  0.01699296,  0.20610108,
        -0.09248074, -0.11208462, -0.82728634, -0.21190638,  0.29256441,
        -0.026

In [10]:
explained_variances = []
for i in range(len(values)):
    explained_variances.append(values[i] / np.sum(values))
 
print(np.sum(explained_variances), '\n', explained_variances)

0.9999999999999999 
 [0.31029283160711657, 0.13389663911394994, 0.011267656409888032, 0.02617599182364146, 0.0330350036041869, 0.04957137906739587, 0.10545655476465113, 0.0681584394287834, 0.0795636546002415, 0.09185019306886358, 0.09073165651128152]


In [12]:
projected = list()
projected.append(X_scaled.dot(vectors.T[0]))
projected.append(X_scaled.dot(vectors.T[1]))
projected.append(X_scaled.dot(vectors.T[8]))
projected.append(X_scaled.dot(vectors.T[9]))
projected.append(X_scaled.dot(vectors.T[10]))
projected.append(X_scaled.dot(vectors.T[6]))

In [13]:
res = pd.DataFrame(projected)

In [14]:
res = res.transpose()

In [15]:
res.head()

0         1         2         3         4         5
0 -1.837902  3.678128  3.230907  0.075933  0.284615  4.769228
1 -1.681694  0.928355  0.045398 -0.145065  0.655138 -0.772907
2 -2.912556  0.482913 -1.053117  0.869567  1.501046  2.373253
3 -2.262620 -0.557104 -1.449247 -0.242818  1.406053  2.871014
4 -2.774952  0.350761 -0.245531 -1.132535  0.820946  0.985732

In [16]:
df = df.join(res)

In [17]:
df.head(2)

acousticness                                               name  \
0         0.702     Kapitel 10 - In der Osternacht Anton Tschechow   
1         0.967  Il a fallu - Récital au Théâtre de L'etoile Yv...   

   danceability     tempo  loudness  energy                      id  \
0         0.586  0.003539 -0.004339   0.103  2bB8AoMI30VKEnF2sVKxrg   
1         0.621  0.002105 -0.002693   0.202  2avT9nqCaGg0EOA1ItgdlK   

   instrumentalness  key  liveness  ...  valence    year          artists  \
0               0.0  5.0    0.7110  ...    0.385  1953.0  Anton Tschechow   
1               0.0  3.0    0.0842  ...    0.453  1953.0     Yves Montand   

                  genres         0         1         2         3         4  \
0  ['german literature'] -1.837902  3.678128  3.230907  0.075933  0.284615   
1            ['chanson'] -1.681694  0.928355  0.045398 -0.145065  0.655138   

          5  
0  4.769228  
1 -0.772907  

[2 rows x 22 columns]

In [18]:
df = df[['name','id','artists','genres','year',0,1,2,3,4,5]]

In [19]:
df.head()

name                      id  \
0     Kapitel 10 - In der Osternacht Anton Tschechow  2bB8AoMI30VKEnF2sVKxrg   
1  Il a fallu - Récital au Théâtre de L'etoile Yv...  2avT9nqCaGg0EOA1ItgdlK   
2       Flute Duet Young Hanunóo girl and her mother  2acrbSyCcVPeE2hFFcxpvd   
3  Mascagni: Cavalleria rusticana: "Tu qui, Santu...  2aZodKpBxuFEODS2npO5lt   
4  Elektra, Op. 58, TrV 223: Wo bleibt Elektra? (...  2auzLo58UkDBZO9CnngDst   

                             artists  \
0                    Anton Tschechow   
1                       Yves Montand   
2  Young Hanunóo girl and her mother   
3                    Pietro Mascagni   
4                    Richard Strauss   

                                              genres    year         0  \
0                              ['german literature']  1953.0 -1.837902   
1                                        ['chanson']  1953.0 -1.681694   
2                                                 []  1953.0 -2.912556   
3  ['classical', 'italian opera', 'post-romantic ...  1953.0 -2.262620   
4  ['classical', 'early modern classical', 'post-...  1953.0 -2.774952   

          1         2         3         4         5  
0  3.678128  3.230907  0.075933  0.284615  4.769228  
1  0.928355  0.045398 -0.145065  0.655138 -0.772907  
2  0.482913 -1.053117  0.869567  1.501046  2.373253  
3 -0.557104 -1.449247 -0.242818  1.406053  2.871014  
4  0.350761 -0.245531 -1.132535  0.820946  0.985732

In [20]:
df.shape

(156581, 11)

In [21]:
df.to_csv('PCADWG.csv')